version: "3.9"

services:
  frontend:
    image: mokchhedul/schoolmanagerfrontend:latest
    ports:
      - "80:80"

  backend:
    image: mokchhedul/schoolmanagerbackend:latest
    environment:
      - JWT_SECRET=mokchhedul
      - MONGO_URI=mongodb+srv://mokchheduls46:mokchhedul@cluster0.cxqeo.mongodb.net/saas?retryWrites=true&w=majority&appName=Cluster0
      - PORT=5000
    ports:
      - "5000:5000"