apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: school-frontend
  namespace: argocd
spec:
  project: default

  source:
    repoURL: https://github.com/mdmokchhedulislam/schoolmanage_devops
    targetRevision: main
    path: k8s/frontend

  destination:
    server: https://kubernetes.default.svc
    namespace: frontend

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true